config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    shared: 'users/shared' }
  resources :users, only: :show

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root to: "static_pages#home"
  namespace :admin do
    resources :categories do
      resources :items
    end
    resources :items
  end
  resources :items, only: %i[index show]

  resources :categories, only: %i[index show] do
    resources :items, only: %i[index show]
  end
  resource :cart, only: [:show]
  resources :order_items, only: %i[create update destroy]
  resources :orders, only: %i[index show]
  get 'orders/:id/cancel_order', to: "orders#cancel_order", as: "cancel_order"
  get 'orders/:id/checkout', to: "orders#checkout", as: "checkout"
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, uniqueness: { message: "%{attribute} has to be unique" }
  validates :description, presence: true
  validates :price,  presence: true, numericality: { greater_than: 0 }

  has_attached_file :picture, styles: { medium: "50x50#" }, default_url: "default_item_pic.jpg"
  validates_attachment_content_type :picture, content_type: /\Aimage/
  validates_attachment_file_name :picture, matches: [/png\z/, /jpe?g\z/]
  validates_attachment_size :picture, less_than: 2.megabytes

  has_many :variations, class_name: "Item", foreign_key: "parent_item_id"
  belongs_to :item, class_name: "Item"
  has_many :options, dependent: :destroy
  has_many :order_items
  has_many :category_items
  has_many :categories, through: :category_items
  belongs_to :user

  accepts_nested_attributes_for :variations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :category_items, reject_if: :all_blank

  searchkick
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < ApplicationController
    before_action :set_item, only: %i[show edit destroy update]
    before_action :admin?

    def show; end

    def index
      @items = Item.all
    end

    def create
      @item = Item.new(item_params)
      if @item.save
        flash[:notice] = "Item created successfully"
        redirect_to root_url
      else
        render :new
        flash.now[:alert] = "Error creating item"
      end
    end

    def new
      @item = Item.new
      @category_item = CategoryItem.new
    end

    def edit; end

    def update
      if @item.update(item_params)
        flash[:notice] = "Item updated!"
        redirect_to @item
      else
        render :edit
        flash.now[:alert] = "Error updating item"
      end
    end

    def destroy
      @item.destroy
      flash[:notice] = "Item deleted!"
      redirect_back(fallback_location: root_url)
    end

    private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description, :price, :picture,
                                   variations_attributes: %i[id title description price o_picture _destroy],
                                   category_items_attributes: %i[id category_id],
                                   options_attributes: [:id, :name, :description, :o_picture,
                                                        :required, :multiple_values, :_destroy,
                                                        values_attributes: %i[id name additional_charge _destroy]])
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit destroy]

  def index
    if params[:query].present?
      @items = Item.search(params[:query], match: :word_start)
    else
      @items = Item.all
    end
    @order_item = current_order.order_items.new
  end

  def show
    @order_item = current_order.order_items.new
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :picture)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def admin_role?
    current_user.try(:admin)
  end

  # item has a parent item?
  def a_variation?(item)
    !item.parent_item_id.nil?
  end
end

app/views/items/_item.html.erb
<% if action_name == "index" || action_name == "home" %>
  <div id="item-<%= action_name %>" class="col-md-2">
    <figure id="item-picture">
      <%= image_tag item.picture.url(:medium), width: 250, alt: item.title, class: "img-responsive" %>
    </figure>
    <div id="item-title">
      <%= link_to item.title, item_path(item) %>
    </div>
    <div id="item-description">
      <%= item.description %>
    </div>
    <div id="item-price">
      <em><%= number_to_currency(item.price, unit: "EG") %></em>
    </div>
    <div id="item-categories">
      <p><small>Categories: 
          <% item.categories.each do |c| %>
            <%= link_to c.title, c %>
          <% end %> 
      </small></p>
    </div>
    <% if admin_role? %>
      <div id="admin-controls">
        <%= link_to "Edit item", edit_admin_item_path(item) %>
        <%= link_to "Delete item", admin_item_path(item), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %> 
  </div>
<% elsif controller_name == "categories"  %>
  <div id="item-<%= action_name %>" class="col-md-3">
    <figure id="item-picture">
      <%= image_tag item.picture.url(:medium), width: 300, alt: item.title, class: "img-responsive" %>
    </figure>
    <div id="item-title">
      <%= link_to item.title, item_path(item) %>
    </div>
    <div id="item-description">
      <%= item.description %>
    </div>
    <div id="item-price">
      <em><%= number_to_currency(item.price, unit: "EG") %></em>
    </div>
    <div id="item-categories">
      <p><small>Categories: 
          <% item.categories.each do |c| %>
            <%= link_to c.title, c %>
          <% end %> 
      </small></p>
    </div>
    <% if admin_role? %>
      <div id="admin-controls">
        <%= link_to "Edit item", edit_admin_item_path(item) %>
        <%= link_to "Delete item", admin_item_path(item), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %> 
  </div>
<% else %>
  <div id="item-<%= action_name %>" class="col-md-4">
    <figure id="item-picture">
      <%= image_tag item.picture.url(:medium), width: 500, alt: item.title, class: "img-responsive" %>
    </figure>
    <div id="item-title">
      <%= link_to item.title, item_path(item) %>
    </div>
    <div id="item-description">
      <%= item.description %>
    </div>
    <div id="item-price">
      <em><%= number_to_currency(item.price, unit: "EG") %></em>
    </div>
    <div id="item-categories">
      <p><small>Categories: 
          <% item.categories.each do |c| %>
            <%= link_to c.title, c %>
          <% end %> 
      </small></p>
    </div>
    <% if admin_role? %>
      <div id="admin-controls">
        <%= link_to "Edit item", edit_admin_item_path(item) %>
        <%= link_to "Delete item", admin_item_path(item), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %> 
  </div>
  <div class="col-md-6">
      <%= render 'cart_form', item: item, order_item: @order_item %>
  </div>
<% end %>

app/views/items/index.html.erb
<div class="row items">
	<div class="col-lg-12">
		<h1>Collection</h1>
		<% if @items.any? %>
			<%= render @items %>
		<% else %>
			<h2>No items found.</h2>
		<% end %>
 	</div>
</div>

app/views/items/show.html.erb
<div class="row item">
	<div class="col-lg-12">
		<%= render @item %>
	</div>
</div> <br/>
<hr>
<div class="row item-variations">
  <div class="col-lg-12">
    <% if !@item.variations.empty? %>
      <h4>Variations of this item</h4>
      <%= render @item.variations %>
    <% end %>
  </div>
</div>