config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    shared: 'users/shared' }
  resources :users, only: :show

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root to: "static_pages#home"
  namespace :admin do
    resources :categories do
      resources :items
    end
    resources :items
  end
  resources :items, only: %i[index show]

  resources :categories, only: %i[index show] do
    resources :items, only: %i[index show]
  end
  resource :cart, only: [:show]
  resources :order_items, only: %i[create update destroy]
  resources :orders, only: %i[index show]
  get 'orders/:id/cancel_order', to: "orders#cancel_order", as: "cancel_order"
  get 'orders/:id/checkout', to: "orders#checkout", as: "checkout"
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { in: 2..150 }
  validates :description, presence: true, length: { in: 3..400 }
  has_many :category_items
  has_many :items, through: :category_items
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    before_action :set_category, only: %i[show edit destroy update]
    before_action :admin?

    def show; end

    def index
      @categories = Category.all
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "category created successfully"
        redirect_to root_url
      else
        render :new
        flash.now[:alert] = "Error creating category"
      end
    end

    def new
      @category = Category.new
    end

    def edit; end

    def update
      if @category.update(category_params)
        flash[:notice] = "category updated!"
        redirect_to @category
      else
        render :edit
        flash.now[:alert] = "Error updating category"
      end
    end

    def destroy
      @category.destroy
      flash[:notice] = "category deleted!"
      redirect_back(fallback_location: root_url)
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit destroy]

  def index
    @categories = Category.all
  end

  def show
    @order_item = current_order.order_items.new
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="category">
	<p id="category-title">
		<h3><%= link_to category.title.titleize, category_path(category) %></h3>
	<p>
	<p id="category-description">
		<i><%= category.description %></i>
	</p>
</div>
<hr>

app/views/categories/index.html.erb
<div class="row category-index">
	<div class="col-lg-12">
		<h1>All categories</h1>
		<%= render @categories %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="row category-show">
	<div class="col-lg-12">
		<h1><%= @category.title %></h1>
		<% if admin_role? %>
			<h6><i>Category ID: <%= @category.id %></i></h6>
			<h5><%= link_to "add item", new_admin_category_item_path(@category) %></h5>
		<% end %>
		<div class="row category-items">
			<%= render @category.items.all %>
		</div>
	</div>
</div>