config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    shared: 'users/shared' }
  resources :users, only: :show

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root to: "static_pages#home"
  namespace :admin do
    resources :categories do
      resources :items
    end
    resources :items
  end
  resources :items, only: %i[index show]

  resources :categories, only: %i[index show] do
    resources :items, only: %i[index show]
  end
  resource :cart, only: [:show]
  resources :order_items, only: %i[create update destroy]
  resources :orders, only: %i[index show]
  get 'orders/:id/cancel_order', to: "orders#cancel_order", as: "cancel_order"
  get 'orders/:id/checkout', to: "orders#checkout", as: "checkout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { in: 2..150 }
  validates :description, presence: true, length: { in: 3..400 }
  has_many :category_items
  has_many :items, through: :category_items
end

app/models/category_item.rb
class CategoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, uniqueness: { message: "%{attribute} has to be unique" }
  validates :description, presence: true
  validates :price,  presence: true, numericality: { greater_than: 0 }

  has_attached_file :picture, styles: { medium: "50x50#" }, default_url: "default_item_pic.jpg"
  validates_attachment_content_type :picture, content_type: /\Aimage/
  validates_attachment_file_name :picture, matches: [/png\z/, /jpe?g\z/]
  validates_attachment_size :picture, less_than: 2.megabytes

  has_many :variations, class_name: "Item", foreign_key: "parent_item_id"
  belongs_to :item, class_name: "Item"
  has_many :options, dependent: :destroy
  has_many :order_items
  has_many :category_items
  has_many :categories, through: :category_items
  belongs_to :user

  accepts_nested_attributes_for :variations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :category_items, reject_if: :all_blank

  searchkick
end

app/models/option.rb
class Option < ApplicationRecord
  validates :name, presence: true
  validates :description, length: { maximum: 400 }
  has_attached_file :o_picture, styles: { medium: "120x120#" }
  validates_attachment_content_type :o_picture, content_type: /\Aimage/
  validates_attachment_file_name :o_picture, matches: [/png\z/, /jpe?g\z/]
  validates_attachment_size :o_picture, less_than: 2.megabytes
  belongs_to :item
  has_many :values, dependent: :destroy

  accepts_nested_attributes_for :values, reject_if: :all_blank, allow_destroy: true
end

app/models/order.rb
class Order < ApplicationRecord
  before_save :update_subtotal
  has_many :order_items, dependent: :destroy
  belongs_to :user
  default_scope { order(created_at: :desc) }

  def subtotal
    order_items.collect { |oi| oi.valid? ? ((oi.quantity * oi.unit_price) + oi.total_additional_charge) : 0 }.sum
  end

  def cancel
    self[:status] = "canceled" if status == "processing"
  end

  def paypal_url(return_path)
    values = {
      business: "merch@dd.com",
      cmd: "_xclick",
      upload: 1,
      return: "localhost:3000#{return_path}",
      invoice: id,
      amount: subtotal
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

  private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :item_present
  validate :order_present
  validate :check_required_options

  before_save :finalize

  include CartsHelper

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_additional_charge
    if order.status == "completed" || order.status == "processing" || order.status == "canceled"
      self[:total_additional_charge]
    else
      calculate_total_additional_charge
    end
  end

  def total_price
    (unit_price * quantity) + total_additional_charge
  end

  def increment_quantity
    self[:quantity] += 1
  end

  private

  def item_present
    errors.add(:item, "is not valid") if item.nil?
  end

  def order_present
    errors.add(:order, "is not a valid order") if order.nil?
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_additional_charge] = total_additional_charge
    self[:total_price] = total_price
  end

  # extras hold the ids of option values selected for the order item
  def calculate_total_additional_charge
    sum = 0
    unless extras.empty?
      extras.each do |value_id|
        value_charge = find_value(value_id).additional_charge
        sum += value_charge
      end
    end
    sum
  end

  # if not at least one value of a required option is present in extras
  # then this required option is not selectd (validation error)
  def check_required_options
    item.options.each do |o|
      if o.required?
        errors.add(o.name.to_s, "is required") unless o.values.any? { |v| extras.include?(v.id.to_s) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :name, presence: true, length: { maximum: 250 }
  has_many :items
  has_many :orders
end

app/models/value.rb
class Value < ApplicationRecord
  validates :name, presence: true
  validates :additional_charge, numericality: { greater_than: -1 }
  belongs_to :option
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit destroy]

  def index
    if params[:query].present?
      @items = Item.search(params[:query], match: :word_start)
    else
      @items = Item.all
    end
    @order_item = current_order.order_items.new
  end

  def show
    @order_item = current_order.order_items.new
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :picture)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[show cancel_order checkout]
  def show; end

  def index
    @orders = Order.all
  end

  def cancel_order
    if @order.cancel
      @order.save
      redirect_to orders_url
      flash[:notice] = "Order canceled successfully!"
    else
      redirect_to orders_url
      flash[:alert] = "Couldn't cancel order"
    end
  end

  def checkout
    redirect_to @order.paypal_url(orders_path)
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def find_value(value_id)
    Value.find_by(id: value_id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def admin_role?
    current_user.try(:admin)
  end

  # item has a parent item?
  def a_variation?(item)
    !item.parent_item_id.nil?
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_category_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <%= render 'admin/shared/error_messages', object: f.object %>
  <fieldset>
  	<%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset> <br/>
  <fieldset>
  	<%= f.label :description %>
  	<%= f.text_area :description, class: "form-control" %>
  </fieldset> <br/>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/admin/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_item_form.html.erb
<%= form_for([:admin, @item], html: { multipart: true }) do |f| %>
  <%= render 'admin/shared/error_messages', object: f.object %>
  <%= render 'item_fields', f: f %>
  <fieldset>
    <%= f.fields_for :options do |option| %>
      <%= render 'option_fields', f: option %>
    <% end %> <br/>
    <h4> <%= link_to_add_association "Add an option to this item", f, :options %> </h4>
  </fieldset>
  <hr>
  <fieldset>
    <%= f.fields_for :variations do |v| %> 
      <%= render 'variation_fields', f: v %>
    <% end %>
    <% unless a_variation?(f.object) %>
      <h4> <%= link_to_add_association 'add a variation of this item', f, :variations %> <h4>
    <% end %>
  </fieldset> <br/>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
  </span>
<% end %>

app/views/layouts/_admin_controls.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Controls <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Add new category", new_admin_category_path %></li>
    <li><%= link_to "Add a new item", new_admin_item_path %></li>
  </ul>
</li>

app/views/layouts/_cart_summary.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal, unit: 'EGP'} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_flash.html.erb
<div class="row">
	<div class="col-lg-8">
		<% flash.each do |message_type, message| %>
		  <%= content_tag :div, class: "alert alert-#{message_type}" do -%>
		  <%= message %>
		  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		  <% end -%>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top header">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">DinnerDash</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><%= link_to "My Orders", orders_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <li><a href="#">Special items</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Contact us</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left items-search-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="search items..." id="query" name="query" />
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if admin_role? %>
            <%= render 'layouts/admin_controls' %>
          <% end %>
          <li><%= link_to "Profile", user_path(current_user)%></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        <li class="cart-summary"> <%= render 'layouts/cart_summary' %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header_homepage.html.erb
<nav class="navbar navbar-default navbar-fixed-top header-homepage">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand" id="logo">
        Groofy
        <span id="groofy-market">Market</span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><%= link_to "My Orders", orders_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <li><a href="#">Special items</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Contact us</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left items-search-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="search items..." id="query" name="query" />
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if admin_role? %>
            <%= render 'layouts/admin_controls' %>
          <% end %>
          <li><%= link_to "Profile", user_path(current_user)%></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        <li class="cart-summary"> <%= render 'layouts/cart_summary' %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groofy Market</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if action_name == "home" %>
      <%= render 'layouts/header_homepage' %>
    <% else %>
     <%= render 'layouts/header' %>
    <% end %>
    <div class="container-fluid wrapper">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>